# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskcluster" do
  version "110.1.0"

  on_macos do
    on_intel do
      sha256 "6e5e80eed425898f30197211a9280f0c4996b41fe49851ced0c04f0e4ced9f43"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-darwin-amd64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
    on_arm do
      sha256 "6ef9ed2e23984cff87c1ee57951906a0d77a4329772f5f517a73f7fff37f3547"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-darwin-arm64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
  end

  on_linux do
    on_intel do
      sha256 "fcd08127de161ebaa6f8085db963b7cb84b1fa2b0e0caa51b28a1ad03bcd3cb8"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-linux-amd64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
    on_arm do
      sha256 "56cc6bb288eacef8713a7736ed9a19ea4628305bb90d93e01bf4c03bbb0d8157"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-linux-arm64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
  end

  name "taskcluster"
  desc "A Taskcluster client library for the command line"
  homepage "https://github.com/taskcluster/taskcluster/tree/main/clients/client-shell"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskcluster"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taskcluster"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To install shell completions, run one of:
      taskcluster completions bash /opt/homebrew/etc/bash_completion.d/taskcluster
      taskcluster completions zsh "$(brew --prefix)/share/zsh/site-functions/_taskcluster"
      taskcluster completions fish "$(brew --prefix)/share/fish/vendor_completions.d/taskcluster.fish"
  EOS
end
