# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskcluster" do
  version "102.0.0"

  on_macos do
    on_intel do
      sha256 "b59e17f1b2208202ae218961d7b51ff360cc2ebd72b9fa2547833f2ec14a8198"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-darwin-amd64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
    on_arm do
      sha256 "a83f442b29c91d1a9d9b0da1420229828af77f359f7c2a07c979291d66a288c8"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-darwin-arm64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
  end

  on_linux do
    on_intel do
      sha256 "861d7b889866d3b71385da68c267c386ca57a8987f1c55493693ea1bc3c62f19"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-linux-amd64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
    on_arm do
      sha256 "a225b5fe19b030b927d3fd3d7d9cebe06fd07524737396fbb8dd59f506dd5593"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-linux-arm64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
  end

  name "taskcluster"
  desc "A Taskcluster client library for the command line"
  homepage "https://github.com/taskcluster/taskcluster/tree/main/clients/client-shell"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskcluster"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taskcluster"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To install shell completions, run one of:
      taskcluster completions bash /opt/homebrew/etc/bash_completion.d/taskcluster
      taskcluster completions zsh "$(brew --prefix)/share/zsh/site-functions/_taskcluster"
      taskcluster completions fish "$(brew --prefix)/share/fish/vendor_completions.d/taskcluster.fish"
  EOS
end
