# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskcluster" do
  version "110.1.0"

  on_macos do
    on_intel do
      sha256 "45722340bdf8ad29f329aaf78f24788a36d5b6d3e928d6c0b2e1dfb20a72b0aa"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-darwin-amd64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
    on_arm do
      sha256 "4708f37d982ea24d859ab1b7b9fc23153673975a6f69351c74c42e211fb717e7"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-darwin-arm64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ade834fa4c1c5d153f61997885d74cee4e9bab8dd1053e72b83e9d79befcf1bc"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-linux-amd64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
    on_arm do
      sha256 "16e3a9a86cfa4653928f70241e447bca14781fc631dc942371632de069b8ceb0"
      url "https://github.com/taskcluster/taskcluster/releases/download/v#{version}/taskcluster-linux-arm64.tar.gz",
        verified: "github.com/taskcluster/taskcluster/"
    end
  end

  name "taskcluster"
  desc "A Taskcluster client library for the command line"
  homepage "https://github.com/taskcluster/taskcluster/tree/main/clients/client-shell"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskcluster"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taskcluster"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To install shell completions, run one of:
      taskcluster completions bash /opt/homebrew/etc/bash_completion.d/taskcluster
      taskcluster completions zsh "$(brew --prefix)/share/zsh/site-functions/_taskcluster"
      taskcluster completions fish "$(brew --prefix)/share/fish/vendor_completions.d/taskcluster.fish"
  EOS
end
